import React from 'react'
import Head from 'next/head'
import Navbar from './Navbar'

const Layout = ({ children }) => {
  return (
    <>
      <Head>
        <title>Urbis Benefits</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <Navbar />
        <main>{children}</main>
      </div>
    </>
  )
}

export default Layout
